---
title: "Example Report"
output: 
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      error = FALSE)
```

```{r}
library(InvestR)
library(ggplot2)
library(kableExtra)
data(ETF)
x <- na.omit(etf_ret[, 1:4])
plot_col <- c('firebrick', 'dodgerblue', 'goldenrod', 'seagreen3')
```

\newpage

# Performance Summary

```{r, fig.height=9, fig.width=7}
viz_perf(x, plot_col = plot_col)
```

\newpage

# Performance Summary

## Periodic Returns

Returns (periods greater than one year are annualized) as of `r zoo::index(x)[nrow(x)]`

```{r}
cal_ret <- tbl_cal_perf(x)
kbl <- kable(cal_ret$fmt)
kable_styling(kbl, latex_options = 'striped')
```

## Calendar Returns

Fund Ticker `r colnames(x)[1]`

```{r}
mon_ret <- tbl_month_ret(x[, 1], dig = 2)
kbl <- kable(mon_ret$fmt)
kbl_in <- kable_styling(kbl)
column_spec(kbl_in, 14, bold = TRUE)
```

## Key Performance Metrics

From `r zoo::index(x)[1]` to `r zoo::index(x)[nrow(x)]`

```{r}
res <- tbl_perf_stat(x[, 1], x[, 2:4], rf)
kbl <- kable(res$fmt)
kable_styling(kbl, latex_options = 'striped')
```



